### ISSUE TITLE
`@deprecated` should be a boolean

### ISSUE THREAD

**Issue by Jason3S** [vega/ts-json-schema-generator#1012]
Thank you for the tool, it is very useful.

I just updated to 0.97.0 today and had unexpected changes to the schema.

Related to #972

```ts
/**
* @deprecated
*/
type MyType = string;
```

Should result in:

```js
   "deprecated": true
```

Not

```js
   "deprecated": ""
```

See: [Generic keywords — Understanding JSON Schema 2020-12 documentation](https://json-schema.org/understanding-json-schema/reference/generic.html) scroll down to `New in draft 2019-09`

**Comment by domoritz** [comment]
Can you isolate the change or even send a pull request? 

Do you have a failing example?

**Comment by Jason3S** [comment]
PR #973 introduced the change.

![image](https://user-images.githubusercontent.com/3740137/140611462-fb576688-4ae8-42b6-aa2e-f0c3883225e8.png)

https://github.com/stevenlandis-rl/ts-json-schema-generator/blob/9ba983fa69699a8de7b8a317c9141a6cff228d27/src/AnnotationsReader/BasicAnnotationsReader.ts#L82

and

![image](https://user-images.githubusercontent.com/3740137/140611471-47820d92-daf7-4568-9dc5-75097b2ebfac.png)

https://github.com/stevenlandis-rl/ts-json-schema-generator/blob/9ba983fa69699a8de7b8a317c9141a6cff228d27/src/AnnotationsReader/ExtendedAnnotationsReader.ts#L70

Turned empty tags into string.

**Comment by Jason3S** [comment]
Looks like PR #984 introduced an incorrect `@deprecated` example.

Note: I understand that [TSDoc: @deprecated](https://tsdoc.org/pages/tags/deprecated/) suggests that it should be a string. I'm just leaning towards making sure the resulting JSON-schema is correct. 

Any thoughts on the "right" behavior? VS Code went with `@deprecationMessage` for the text.

**Comment by domoritz** [comment]
@stevenlandis-rl what do you think?

**Comment by stevenlandis-rl** [comment]
I remember looking into this and it's a little strange. For schema version 7 which is currently used by this generator, the `@deprecated` tag can be anything. For schema version 2019-09 and on, `@deprecated` has to be a boolean [[source](http://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.3)].

I went with keeping empty `@deprecated` tags as undefined since it is simpler and consistent with how we handle other empty tags, but the forward-looking approach is to restrict `@deprecated` tags to be a boolean.

**Comment by domoritz** [comment]
Let's be forward-looking. Anyone up for a quick pull request?

**Comment by domoritz** [comment]
Anyone wants to help @stevenlandis-rl @Jason3S?
