### ISSUE TITLE
Parsing all types in a file with *

### ISSUE THREAD

**Issue by tommitytom** [vega/ts-json-schema-generator#117]
Currently I use the following command to generate a schema:
`ts-json-schema-generator --path test.ts --type MyInterface`

However, instead of just generating a schema containing `MyInterface`, is it possible to collect all types within `test.ts` and write them in to the same schema?

**Comment by domoritz** [comment]
Part of https://github.com/vega/ts-json-schema-generator/issues/104

**Comment by andreashuber69** [comment]
@domoritz I'm trying to implement this right now. However, the code I'm currently looking at makes things more complicated than they should be (IMHO) and I constantly find myself itching to simplify. Would you also accept a refactoring PR that just simplifies things so that I can implement this more cleanly in a second PR?

**Comment by domoritz** [comment]
Definitely! I love refactoring PRs.

**Comment by andreashuber69** [comment]
> Definitely! I love refactoring PRs.

Ok, here it is: https://github.com/vega/ts-json-schema-generator/pull/129

**Comment by HoldYourWaffle** [comment]
Good to see there's progress on this!

**Comment by domoritz** [comment]
I merged #129.

**Comment by andreashuber69** [comment]
> I merged #129.

Thank you! I inadvertently pushed additional commits to master before you merged, which is why this is now already implemented, at least to the degree that it now works with a trivial example. Simply omit the `--type` argument or set it to `*` and the generated schema should now contain all root types.

However, things currently only work by chance. Namely, quite a bit of code assumes that `Config.type` is a string (i.e. not `null` and not `undefined`), but of course omitting the `--type` argument leads to `Config.type` being `undefined`.

To see what I'm talking about, please declare `Config.type` as `string | undefined` and then adapt dependent code accordingly. You will quickly arrive at the conclusion that `BaseType.getName()` should also have a return type of `string | undefined`. However declaring like so leads to further errors.

A trivial fix could be to implement `DefinitionType.getName()` as follows:

```
    public getName() {
        return this.name || super.getName();
    }
```
(See [this commit](https://github.com/andreashuber69/ts-json-schema-generator/commit/ff15fa972719e927416a2916af7d7e364dc5dc02) for details.)

I currently lack the insight to determine whether this is a good idea. Any hints or pointers would be greatly appreciated!

**Comment by domoritz** [comment]
Ups. 

I don't think we want to change the `DefinitionType`. I think this would mean that the definition type doesn't have a name. Maybe I am missing something but to me it's a bit of a mystery why this change would allow us to get all root types. 

Can you find a different implementation? If you look at https://github.com/YousefED/typescript-json-schema/blob/17f22769f3556776fa1fad27f47b5266083d89c6/typescript-json-schema.ts#L1167, you can see that we essentially iterate over the root types.

**Comment by andreashuber69** [comment]
> I don't think we want to change the `DefinitionType`. I think this would mean that the definition type doesn't have a name. Maybe I am missing something but to me it's a bit of a mystery why this change would allow us to get all root types.

There seems to be a misunderstanding. The code that puts all root types into a schema is already merged (and published with the 0.47 release, AFAICT). Of course, this was not intended, see my last post. The function that makes the distinction one type vs. all root types is here:

https://github.com/vega/ts-json-schema-generator/blob/eb04762b2385b81aac1e56e7bfb0bf91872eb2eb/src/SchemaGenerator.ts#L32

However, this is not a clean implementation, primarily because the types are lying (i.e. `Config.type` can be `undefined`, etc. see above), which is what I'm trying to correct now.

> Can you find a different implementation? If you look at https://github.com/YousefED/typescript-json-schema/blob/17f22769f3556776fa1fad27f47b5266083d89c6/typescript-json-schema.ts#L1167, you can see that we essentially iterate over the root types.

Thanks, I will have a look at that later.

**Comment by domoritz** [comment]
I see. Let's fix the types then. Can you send a PR? Instead of `foo: X | undefined`, can you use `foo?: X`?

**Comment by andreashuber69** [comment]
> I see. Let's fix the types then. Can you send a PR?

Ok, here's the PR: https://github.com/vega/ts-json-schema-generator/pull/135

> Instead of `foo: X | undefined`, can you use `foo?: X`?

I intentionally did not do that because `name?` in a parameter list means that the parameter is optional. Since `name` is not the last parameter, this would not work. So `string | undefined` is more consistent. Feel free to adapt if you'd rather see `type?: string;` in `Config`.

Finally, also feel free to revert commit https://github.com/vega/ts-json-schema-generator/commit/a4ce8ccd731b0fa51faef031e41ef8905d0a101a if you think this is going into the wrong direction. I'd be happy to start over.
