### ISSUE TITLE
LogicError: Unexpected type "("ArrayBuffer")"

### ISSUE THREAD

**Issue by sparebytes** [vega/ts-json-schema-generator#131]
An error is produced when generating from a `Buffer` type.

Input:
```ts
export interface DataBox {
    data: Buffer;
}
```

Error:
```
LogicError: Unexpected type "("ArrayBuffer")" (expected "LiteralType" or "StringType" or "NumberType")
```

I made a minimal code base to show the error: https://github.com/sparebytes/bug-report-ts-json-schema-generator

P.S. I'm working on a Typscript tansformer that uses this library and AJV to emit validation functions directly into javascript: [typesmith](https://www.npmjs.com/package/typesmith). It's coming together surprisingly well thanks to how awesome `ts-json-schema-generator` is. 😀

**Comment by domoritz** [comment]
Thank you for your kind words. I'm glad this library is useful for you. 

Looks like this is happening in https://github.com/vega/ts-json-schema-generator/blob/19c778b9f07da22b2bf6841218f3485eebce7b6f/src/NodeParser/IndexedAccessTypeNodeParser.ts#L23.

**Comment by domoritz** [comment]
Even simpler test case `export type DataBox = Buffer;`

**Comment by domoritz** [comment]
Also `export type DataBox = Uint8Array;`

**Comment by kayahr** [comment]
I don't really understand what this typesmith actually does and why it is useful for it to have a JSON schema with the internal properties of a typed array in it but that doesn't really matter when we just look at the core problem:

```
interface Types {
    String: string;
}

export type MyObject = Types[keyof Types];
```

When we fix this (And the PR does that) then it also works with Uint8Array.

But it probably will cause trouble again in the future because it stops working when more types are added to the `Types` interface:

```
interface Types {
    String: string;
    Number: number;
}
export type MyObject = Types[keyof Types];
```
Error:

```
LogicError: Unexpected type "("String"|"Number")" (expected "LiteralType" or "StringType" or "NumberType")
```

So when we want to fix it properly then the change in the PR is not enough.

**Comment by kayahr** [comment]
I just created PR #137 which implements proper union type support for indexed access which works with both examples from my last comment.
