### ISSUE TITLE
Add compilation to older drafts

### ISSUE THREAD

**Issue by celicoo** [vega/ts-json-schema-generator#184]
Hey, it would be very nice to allow compilation to older drafts. Right now my team is using a fork of [YousefED/typescript-json-schema](https://github.com/YousefED/typescript-json-schema) to compile interfaces that represent the body of a request to the draft-04. We use the schemas as [API Gateway request validators](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-method-request-validation.html), which only accepts draft-04.

**Comment by domoritz** [comment]
You can just change the draft version. I don't think we use any advanced features.

**Comment by celicoo** [comment]
@domoritz [Open–closed principle(https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle)

**Comment by domoritz** [comment]
In this case, you can just generate the schema and then modify the generated object. This should work since the draft versions don't differ much. Since I don't have the cycles to maintain compatibility with older versions, I don't want to give the impression that we support older versions. I'm well aware of software patterns but in this case it's development constraints.
