### ISSUE TITLE
Problems with generic types

### ISSUE THREAD

**Issue by max-leuthaeuser** [vega/ts-json-schema-generator#209]
Trying to use e.g., react from `DefinitelyTyped/types/react/` as input with:
```
ts-json-schema-generator -p "DefinitelyTyped/types/react/*.ts" -f "DefinitelyTyped/types/react/tsconfig.json"
```
fails with:
```
Error: Unknown node "JSXElementConstructor<any>" (ts.SyntaxKind = 167) at DefinitelyTyped/types/react/index.d.ts(98,93)
```

The generic type used there looks like this:
```typescript
type JSXElementConstructor<P> =
        | ((props: P) => ReactElement | null)
        | (new (props: P) => Component<P, any>);

interface ReactElement<P = any, T extends string | JSXElementConstructor<any> = string | JSXElementConstructor<any>> {
        type: T;
        props: P;
        key: Key | null;
    }
```

Whats the problem here?

**Comment by domoritz** [comment]
You can look in the typescript source to find out what SyntaxKind 167 is. I suspect the issue here is that you're trying to create a schema with functions and constructors.

**Comment by max-leuthaeuser** [comment]
Yes, tried it with functions and methods. So, I guess this can be closed too.

**Comment by itelo** [comment]
Hi, every time my type/interface uses React types this error appears, @max-leuthaeuser do you find a way to solve this?

**Comment by max-leuthaeuser** [comment]
No. Unfortunately, not.

**Comment by cdaringe** [comment]
it would be great to have an option to just _skip_ such things.  when running https://github.com/YousefED/typescript-json-schema against my `src/client.ts`, it generates all the associated schema definitions, regardless of the fact that there are _more_ symbols and nodes that dont boil down to schema definitions.  even _better_?--allow a way (perhaps a hook or something)--such that i can react to those types/events.

in my use . case, i'm parsing a library in order to generate a swagger.json (not used for a server, but a codegen tool), and i need to map such functions into [swagger paths](https://swagger.io/docs/specification/paths-and-operations/).  `typescript-json-schema` fills out the bottom half of my `swagger.json`, and these other _kind_s make up the missing top half!
