### ISSUE TITLE
Incorrect output for intersection type 

### ISSUE THREAD

**Issue by kanitw** [vega/ts-json-schema-generator#58]
In Vega-Lite, `MarkPropFieldDef`'s `bin` property should not support `"binned"` as its value.  However, the generated JSON schema includes `"binned"`.

**Comment by kanitw** [comment]
https://github.com/vega/vega-lite/pull/4437#discussion_r244629934 is another instance of this issue.

**Comment by domoritz** [comment]
Do you have a small test case?

**Comment by kanitw** [comment]
You can copy the declaration for `FieldDefWithoutScale` and simplify -- it's already small enough.

**Comment by kayahr** [comment]
Maybe someone familiar with Vega can do this "simplification" and post the simplified test case here so people unrelated to vega can try to help? I tried and gave up after following dozens of other types... Mabye this bug is the same as #115 I reported a few weeks ago but I can't be sure without a proper bug description.

**Comment by domoritz** [comment]
It does sound a lot like #115. Once it's fixed, I will confirm that it resolves this issue or otherwise add a better test case, okay?

**Comment by domoritz** [comment]
https://github.com/vega/vega-lite/pull/4437#discussion_r244629934 is correct now. I can't find "MarkPropFieldDef"'s definition in the schema. I think this is correct now.
