### ISSUE TITLE
Error in v0.83.0

### ISSUE THREAD

**Issue by satvik-s** [vega/ts-json-schema-generator#626]
Getting the following error when using v0.83

```
Error: Cannot find module '../dist/ts-json-schema-generator'
Require stack:
- /usr/src/app/node_modules/ts-json-schema-generator/bin/ts-json-schema-generator
```

On checking `node_modules` it looks like that `dist/ts-json-schema-generator` no longer is present in latest version unlike previous versions

**Comment by domoritz** [comment]
Hmm, strange. I'll fix it tomorrow. Thanks for the bug report.

**Comment by domoritz** [comment]
Arg, I think I know what the problem is. I added the version to teh package, which includes the package.json in the dist folder, which in turn has a `files` property, which restricts what files are included in the bundle. 

I fixed a similar issue in https://github.com/vega/vega-lite/commit/72d6b10c3bbe38286e64c50e53a358cf48b06d2d.
