### ISSUE TITLE
Generate schema for inline function parameter/s

### ISSUE THREAD

**Issue by simonlovesyou** [vega/ts-json-schema-generator#733]
I'd like to generate JSON schema for input arguments for \~some\~ function, but I can't guarantee that the type parameter/s is a type reference. Example:
```ts
// add.ts
export const add = (numA: number, numB: number) => numA + numB
```
I'd like to either programmatically, or through the CLI, define that I'd like the JSON schema for the parameters of function `add`:
```
yarn ts-json-schema-generator --path ./add.ts --type 'Parameters<typeof add>' 
```

WDYT?

**Comment by domoritz** [comment]
Functions are generally impossible since JSON schema does not have function support. See https://github.com/vega/ts-json-schema-generator/issues/98#issuecomment-498040496. 

If you want just the parameters, you could already define a new type alias for `Parameters<typeof add>`. I'm not sure whether we support it yet but I would be happy to consider a pull request that adds support for it.

**Comment by simonlovesyou** [comment]
> If you want just the parameters, you could already define a new type alias for Parameters<typeof add>

I'm building a library that uses `ts-json-schema-generator`, and can't guarantee that the user is using type references for their function arguments. I'll see if I can make a PR for this functionality :)
